ci:
  collect:
    url:
      - http://localhost:58961
    startServerCommand: npm run start
    numberOfRuns: 3
  assert:
    preset: lighthouserc
    reccommended: true
  upload:
    target: 'temporary-public-storage'
